# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [9]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C
    not found = FMA3,AVX2

#### 3. Create a null vector of size 10

In [14]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [18]:
a=arr.size
b=arr.itemsize
print(str(a*b)+" Bytes")

80 Bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [26]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [21]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [33]:
arr=np.arange(10,50,5)  #init,n,step
print(arr)

[10 15 20 25 30 35 40 45]


#### 8.  Reverse a vector (first element becomes last)

In [35]:
np.flipud(arr)  # or arr[::-1]

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [37]:
arr=np.random.randint(0,9,(3,3))  #arr=np.arange(9).reshape(3,3) it gives 1 to 8 in sequence order
print(arr)

[[6 6 6]
 [6 6 2]
 [8 6 1]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [41]:
arr = np.array([1,2,0,0,4,0])
#ans = np.where(arr!=0)
ans =  np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [44]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [49]:
arr=np.random.random((3,3,3))
arr

array([[[0.71001904, 0.68692406, 0.57489118],
        [0.98105289, 0.21492834, 0.03952937],
        [0.78428962, 0.0807126 , 0.94099465]],

       [[0.79699881, 0.52672041, 0.0375038 ],
        [0.53964428, 0.90167938, 0.9565122 ],
        [0.72384629, 0.88993428, 0.98265592]],

       [[0.60205974, 0.69558031, 0.50655542],
        [0.70230438, 0.05073664, 0.11795668],
        [0.01801851, 0.85304609, 0.12728217]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [56]:
arr=np.random.random((10,10))
a=np.min(arr)
b=np.max(arr)
print(a,b,sep="\n")

0.005087671208089173
0.9859603873461633


#### 14. Create a random vector of size 30 and find the mean value

In [61]:
arr=np.random.random((30))
np.mean(arr)

0.5532218249503627

#### 15. Create a 2d array with 1 on the border and 0 inside

In [66]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [67]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [68]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [73]:
ans = np.diag([1,2,3,4],-1)
ans


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [75]:
ans = np.zeros((8,8),dtype=int)  # no dtype gives float
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [76]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)