In [1]:
import numpy as np
np.array?


In [2]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a[1:,1:3]

array([[5, 6]])

In [8]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

In [12]:
b=np.array([[1,2,3],[4,5,6]])
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
a=np.array([[3,5,2],[7,9,5],[4,1,0]])
a

array([[3, 5, 2],
       [7, 9, 5],
       [4, 1, 0]])

In [15]:
np.sort(a,axis=0)//column sort

array([[3, 1, 0],
       [4, 5, 2],
       [7, 9, 5]])

In [16]:
np.sort(a)//row sort

array([[2, 3, 5],
       [5, 7, 9],
       [0, 1, 4]])

In [19]:
np.sort(a,axis=1,kind='mergesort')

array([[2, 3, 5],
       [5, 7, 9],
       [0, 1, 4]])

In [32]:
dtypes=[('name','S10'),('grand_year',int),('cgpa',float)]
values=[('daniel',2009,8.5),('praveen',2007,9.8)]
arr=np.array(values,dtype=dtypes)
arr

array([(b'daniel', 2009, 8.5), (b'praveen', 2007, 9.8)],
      dtype=[('name', 'S10'), ('grand_year', '<i4'), ('cgpa', '<f8')])

In [33]:
np.sort(arr,order='name')

array([(b'daniel', 2009, 8.5), (b'praveen', 2007, 9.8)],
      dtype=[('name', 'S10'), ('grand_year', '<i4'), ('cgpa', '<f8')])

In [34]:
np.sort(arr)

array([(b'daniel', 2009, 8.5), (b'praveen', 2007, 9.8)],
      dtype=[('name', 'S10'), ('grand_year', '<i4'), ('cgpa', '<f8')])

In [42]:
a=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])


In [43]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [45]:
np.hsplit(a,3)

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]),
 array([[ 9, 11],
        [10, 12]])]

In [48]:
a=np.array([[1,2],[3,4]])
b=np.array([[9,6],[7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [9, 6],
       [7, 8]])

In [49]:
np.hstack((a,b))

array([[1, 2, 9, 6],
       [3, 4, 7, 8]])